---
title: "Clustering"
output: html_notebook
---

Notebook for clustering CRISPR data. 
Load packages. 

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(stringr)
library(harmony)
library(ggplot2)
library(cowplot)
```

### Pre-processing raw seurat objects

```{r}
load("/datastore_share/Users/mayho/meis2_paper/seurat_objects/E16_embryonic_processed_raw.RData")
```

```{r}
E16 <- merge(x = ED200806, y = c(ED210204, ED210215, ED210415, ED211111, ED211124)) 
```


```{r}
E16 <- SCTransform(E16, method = "glmGamPoi", vars.to.regress = c("percent.mt", "nFeature_RNA", "nCount_RNA"), verbosity = TRUE)
```

```{r}
E16 <- E16  %>%
  RunPCA(npcs = 30, verbose = F) %>% 
  RunUMAP(dims = 1:30, verbose = F) %>%
  FindNeighbors(dims = 1:30, verbose = F) %>%
  FindClusters(verbose = F, resolution = 0.8)

DimPlot(E16, group.by = "seurat_clusters") 
```
### Harmony & Integration

```{r}
options(repr.plot.height = 5, repr.plot.width = 12)
p1 <- DimPlot(object = E16, reduction = "pca", pt.size = .1, group.by = "dataset")
p2 <- VlnPlot(object = E16, features = "PC_1", group.by = "dataset", pt.size = .1)
plot_grid(p1,p2)
```

```{r}
options(repr.plot.height = 2.5, repr.plot.width = 6)
E16 <- E16 %>% 
    RunHarmony("dataset", plot_convergence = TRUE, assay.use = "SCT")
```

```{r}
# harmony embeddings
harmony_embeddings <- Embeddings(E16, 'harmony')
harmony_embeddings[1:5, 1:5]
```
```{r}
options(repr.plot.height = 5, repr.plot.width = 12)
p1 <- DimPlot(E16, reduction = "harmony", pt.size = .1, group.by = "dataset")
p2 <- VlnPlot(E16, features = "harmony_1", group.by = "dataset", pt.size = .1)
plot_grid(p1,p2)
```

```{r}
ElbowPlot(E16, ndims = 30)
```

```{r}
E16 <- E16 %>% 
    RunUMAP(reduction = "harmony", dims = 1:30) %>% 
    FindNeighbors(reduction = "harmony", dims = 1:30) %>% 
    FindClusters(resolution = 0.8) %>% 
    identity()
```

```{r}
p1 <- DimPlot(E16, group.by = "dataset")
plot_grid(p1, p2)
```
### CellType Annotation

```{r}
ctrl <- subset(E16, subset = gRNA == "glacZ")
ctrl
```

```{r}
Idents(ctrl) <- "seurat_clusters"
ctrl.markers <- FindAllMarkers(ctrl, only.pos = TRUE, logfc.threshold = 0.25, verbose = FALSE)
top10 <- ctrl.markers %>% group_by(cluster) %>% dplyr::top_n(n = 10, wt = avg_log2FC)
```

Annotate clusters using http://mousebrain.org.


```{r}
 # md is the excel sheet with two columns; seurat_clusters and assignment
E16@meta.data$assign<- plyr::mapvalues(E16@meta.data$SCT_snn_res.0.8, from = md$Cluster, to = md$Assignment)
```


